### ISSUE TITLE
python error in footprints .gpkg creation

### ISSUE THREAD

**Issue by corteza10** [caliskanmurat/qgis_sentinel2_image_downloader_plugin#1]
Hi,

Couldn't create a valid footprints .gpkg in Qgis 3.38 with Windows10, had a python error :

2024-08-14T09:47:25     WARNING    Traceback (most recent call last):
              File "C:\Users/*******/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\sentinel_downloader\sentinel_downloader.py", line 705, in executeFootprints
              self.createGPKG(products_all, fr"{outFolderPath}/{out_name}.gpkg", driver_name = "GPKG")
              File "C:\Users/*******/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\sentinel_downloader\sentinel_downloader.py", line 277, in createGPKG
              feat.SetField('id', e)
              File "C:\PROGRA~1\QGIS33~1.0\apps\Python312\Lib\site-packages\osgeo\ogr.py", line 3871, in SetField
              return _ogr.Feature_SetFieldInteger64(self, fld_index, args[1])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             RuntimeError: Invalid index : -1
             
   
   [footprints_20240704_20240814_25_L2A.txt](https://github.com/user-attachments/files/16609377/footprints_20240704_20240814_25_L2A.txt)

**Comment by caliskanmurat** [comment]
Hello,
I made an update. Can you try new version of plugin after it is approved.

**Comment by corteza10** [comment]
Great ! Successfully downloaded the images, thanks for the update !
